<script src="<?= asset('vendor/js/jquery.min.js') ?>"></script>
<script src="<?= asset('vendor/js/bootstrap.bundle.min.js') ?>"></script>
<script src="<?= asset('vendor/js/adminlte.min.js') ?>"></script>
<script src="<?= asset('js/browser-compat.js') ?>"></script>
<script src="<?= asset('vendor/js/jquery.dataTables.min.js') ?>"></script>
<script src="<?= asset('vendor/js/dataTables.bootstrap4.min.js') ?>"></script>
<script src="<?= asset('vendor/js/jszip.min.js') ?>"></script>
<script src="<?= asset('vendor/js/dataTables.buttons.min.js') ?>"></script>
<script src="<?= asset('vendor/js/buttons.bootstrap4.min.js') ?>"></script>
<script src="<?= asset('vendor/js/buttons.html5.min.js') ?>"></script>
<script src="<?= asset('vendor/js/buttons.print.min.js') ?>"></script>
<script src="<?= asset('vendor/js/chart.umd.min.js') ?>"></script>
<script src="<?= asset('vendor/js/sweetalert2.min.js') ?>"></script>
<script src="<?= asset('js/risfm.js') ?>"></script>
